---

- name: Update APT cache
  apt: update_cache=yes

- name: Install APT certificates
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Docker GPG key
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Add Docker Project repo
  copy:
    src=etc/apt/sources.list.d/docker.list dest=/etc/apt/sources.list.d/docker.list

- name: Update APT cache
  apt: update_cache=yes

- name: Install Docker Engine
  apt: name=docker-engine state=present

- name: Start Docker service
  service: name=docker state=started

- name: Add ubuntu user to docker group
  user: name=ubuntu group=docker

- name: Install docker-py
  pip: name=docker-py